config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|pl/ do
    root 'home#index'

    get '/sign_in', to: 'user_sessions#new', as: :sign_in
    post '/sign_in', to: 'user_sessions#create'
    delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out

    resources :warehouses
    resources :users do
      get '/user_status_info', to: 'users#statuses', as: :get_user_status
      put '/user_status', to: 'users#update_status', as: :update_user_status
    end
    resources :items do
      resources :item_locations
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role

  delegate :name, :to => :role, :prefix => true, :allow_nil => false

  acts_as_authentic
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource :only => [:index, :show, :new, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(create_params)

    if @user.save
      flash[:success] = t 'flashes.save.success'

      redirect_to root_path
    else
      flash[:error] = t 'flashes.save.error'

      render :new
    end
  end

  def update
    if @user.update_attributes(update_params)
      flash[:success] = t 'flashes.update.success'

      redirect_to show
    else
      flash[:error] = t 'flashes.update.error'

      render :show
    end
  end

  def statuses
    @user = User.find(params[:user_id])
  end

  def update_status
    @user = User.find(params[:user_id])

    if @user.update_attributes(update_params)
      flash[:success] = t 'flashes.update.success'
    else
      flash[:error] = t 'flashes.update.error'
    end
  end

  private
    def create_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:active, :approved, :confirmed)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def toggle_user_status(user, status)
    link_to user_update_user_status_path(user, "user[#{status}]" => !user.read_attribute(status)), :method => 'put', :remote => true, :class => 'update-user-status-action' do
      button_title(user.read_attribute(status), status)
    end
  end

  private
    def button_title(bool, status)
      if bool
        icon = fa_icon 'times', class: 'text-danger'
        text = t "actions.user.#{status}.f"
      else
        icon = fa_icon 'check', class: 'text-success'
        text = t "actions.user.#{status}.t"
      end

      [icon, text].join('&nbsp;').html_safe
    end
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <fieldset class="form-group">
      <%= f.label :email, :class => 'form-control-label' %>
      <%= f.email_field :email, :class => 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :password, :class => 'form-control-label' %>
      <%= f.password_field :password, :class => 'form-control' %>
    </fieldset>
    <fieldset class="form-group">
      <%= f.label :password_confirmation, :class => 'form-control-label' %>
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </fieldset>
    <fieldset class="form-group pull-right">
      <%= link_to users_path, :class => 'btn btn-danger' do %>
          <%= fa_icon 'undo' %>&nbsp;<%= t 'actions.cancel' %>
      <% end %>
      <%= button_tag(:class => 'btn btn-success') do %>
          <%= fa_icon 'save' %>&nbsp;<%= t 'actions.save' %>
      <% end %>
    </fieldset>
<% end %>

app/views/users/_form_details.html.erb
<%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <fieldset class="form-group">
      <%= f.label :email, :class => 'form-control-label' %>
      <%= f.email_field :email, :class => 'form-control', :readonly => true %>
    </fieldset>
    <fieldset class="form-group">
      <div class="checkbox">
        <label>
          <%= f.check_box :active %> <%= t 'helpers.label.user.active' %>
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :approved %> <%= t 'helpers.label.user.approved' %>
        </label>
      </div>
      <div class="checkbox">
        <label>
          <%= f.check_box :confirmed %> <%= t 'helpers.label.user.confirmed' %>
        </label>
      </div>
    </fieldset>
    <fieldset class="form-group pull-right">
      <%= link_to user_path(@user), :class => 'btn btn-danger' do %>
          <%= fa_icon 'undo' %>&nbsp;<%= t 'actions.cancel' %>
      <% end %>
      <%= button_tag(:class => 'btn btn-success') do %>
          <%= fa_icon 'save' %>&nbsp;<%= t 'actions.save' %>
      <% end %>
    </fieldset>
<% end %>

app/views/users/_statuses.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <h4 class="modal-title"><%= t 'actions.user.chane_statuses' %></h4>
</div>
<div class="modal-body">
  <%= toggle_user_status(@user, 'active') %>
  <br>
  <%= toggle_user_status(@user, 'approved') %>
  <br>
  <%= toggle_user_status(@user, 'confirmed') %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t 'actions.done' %></button>
</div>

app/views/users/edit.html.erb
<% provide(:title, (t 'users.title.update')) %>

<h1><%= t 'users.title.update' %></h1>

<div class="col-md-6 col-sm-12">
  <%= render 'form_details' %>
</div>

app/views/users/index.html.erb
<% provide(:title, (t 'users.title.index')) %>

<h1>
  <%= t 'users.title.index' %>
  <%= link_to new_user_path, :class => 'btn btn-warning pull-right' do %>
      <%= fa_icon 'plus' %>&nbsp;<%= t 'users.title.new' %>
  <% end %>
</h1>
<% if @users.blank? %>
    <%= render 'shared/no_results' %>
<% else %>
  <table class="table table-bordered table-striped table-hover">
    <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th><%= t 'helpers.label.user.email' %></th>
      <th class="text-xs-center"><%= t 'helpers.label.user.active' %></th>
      <th class="text-xs-center"><%= t 'helpers.label.user.approved' %></th>
      <th class="text-xs-center"><%= t 'helpers.label.user.confirmed' %></th>
      <th class="text-xs-center"><%= fa_icon 'cogs' %></th>
    </tr>
    </thead>
    <tbody>
    <% @users.each_with_index do |user, index| %>
        <tr class="row-linkable" data-url="<%= users_path(user) %>">
          <th scope="row"><%= index + 1 %></th>
          <td><%= user.email %></td>
          <td class="text-xs-center"><%= bool_icon(user.active) %></td>
          <td class="text-xs-center"><%= bool_icon(user.approved) %></td>
          <td class="text-xs-center"><%= bool_icon(user.confirmed) %></td>
          <td class="text-xs-center">
            <ul class="list-inline">
              <li class="list-inline-item">
                <%= action_update_user_status user_get_user_status_path(user) %>
              </li>
              <li class="list-inline-item">
                <%= action_show user_path(user) %>
              </li>
              <li class="list-inline-item">
                <%= action_edit edit_user_path(user) %>
              </li>
              <li class="list-inline-item">
                <%= action_delete user_path(user) %>
              </li>
            </ul>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <div id="user-status-modal" class="modal fade">
    <div class="modal-dialog" role="document">
      <div id="user-status-actions" class="modal-content">
      </div>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, (t 'users.title.new')) %>

<h1><%= t 'users.title.new' %></h1>

<div class="col-md-6 col-sm-12">
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<% provide(:title, (t 'users.title.show')) %>

<h1><%= t 'users.title.show' %></h1>

<div class="col-md-6 col-sm-12">
  <table class="table table-bordered table-hover">
    <tbody>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.email' %></th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.created_at' %></th>
        <td><%= @user.created_at.strftime('%F %T') %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.active' %></th>
        <td><%= bool_icon(@user.active) %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.approved' %></th>
        <td><%= bool_icon(@user.approved) %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.confirmed' %></th>
        <td><%= bool_icon(@user.confirmed) %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.login_count' %></th>
        <td><%= @user.login_count %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.last_login_at' %></th>
        <td><%= @user.last_login_at && @user.last_login_at.strftime('%F %T') %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.role' %></th>
        <td><%= @user.role_name %></td>
      </tr>
      <tr>
        <th class="th-inverse"><%= t 'helpers.label.user.permissions' %></th>
        <td>
          <% @user.role.permissions.each do |permission| %>
              <%= permission.code %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= link_to users_path, :class => 'btn btn-secondary' do %>
      <%= fa_icon 'list' %>&nbsp;<%= t 'actions.list' %>
  <% end %>
  <%= link_to edit_user_path(@user), :class => 'btn btn-primary pull-right' do %>
      <%= fa_icon 'wrench' %>&nbsp;<%= t 'actions.edit' %>
  <% end %>
</div>

app/views/users/statuses.js.erb
$('#user-status-actions').html("<%= escape_javascript(render 'statuses') %>");
$('#user-status-modal').modal('show');

app/views/users/update_status.js.erb
$('#user-status-actions').html("<%= escape_javascript(render 'statuses') %>");