config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|pl/ do
    root 'home#index'

    get '/sign_in', to: 'user_sessions#new', as: :sign_in
    post '/sign_in', to: 'user_sessions#create'
    delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out

    resources :warehouses
    resources :users do
      get '/user_status_info', to: 'users#statuses', as: :get_user_status
      put '/user_status', to: 'users#update_status', as: :update_user_status
    end
    resources :items do
      resources :item_locations
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= t 'misc.form_error' %> <%= t('misc.errors', :count => object.errors.count) %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<ul class="nav navbar-nav">
  <%= link_to root_path, :class => 'navbar-brand' do %>
    <%= fa_icon 'home' %>&nbsp;<%= t 'home.title.index' %>
  <% end %>
  <li class="nav-item">
    <%= locale_switcher %>
  </li>
  <% navigation_data.each do |name, path| %>
    <%= content_tag :li, (link_to (t name), path, :class => 'nav-link'), :class => (current_controller?(path) ? 'nav-item active' : 'nav-item') %>
  <% end %>
</ul>

<ul class="nav navbar-nav pull-right">
  <% if current_user %>
    <li class="nav-item"><%= link_to [(t 'actions.logout'), current_user.email].join(' '), sign_out_path, method: :delete, class: 'nav-link' %></li>
  <% else %>
    <li class="nav-item"><%= link_to (t 'actions.login'), sign_in_path, class: 'nav-link' %></li>
  <% end %>
</ul>

app/views/shared/_no_results.html.erb
<div class="alert alert-warning text-xs-center" role="alert">
  <%= fa_icon 'exclamation-triangle' %>&nbsp;<%= t 'no_results' %>
</div>