config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|pl/ do
    root 'home#index'

    get '/sign_in', to: 'user_sessions#new', as: :sign_in
    post '/sign_in', to: 'user_sessions#create'
    delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out

    resources :warehouses
    resources :users do
      get '/user_status_info', to: 'users#statuses', as: :get_user_status
      put '/user_status', to: 'users#update_status', as: :update_user_status
    end
    resources :items do
      resources :item_locations
    end
  end
end

app/models/item_location.rb
class ItemLocation < ActiveRecord::Base
  IN_STOCK = 'in_stock'.freeze
  INBOUND = 'inbound'.freeze
  OUTBOUND = 'outbound'.freeze
  RESERVED = 'reserved'.freeze

  belongs_to :item, inverse_of: :item_locations
  belongs_to :warehouse, inverse_of: :item_locations

  scope :in_state, ->(warehouse, state) { where(warehouse: warehouse, state: state) }

  delegate :name, :to => :item, :prefix => true, :allow_nil => false

  def self.available_states
    [ IN_STOCK, INBOUND, OUTBOUND, RESERVED ]
  end
end

app/controllers/item_locations_controller.rb
class ItemLocationsController < ApplicationController
  load_and_authorize_resource :only => [:index, :show, :new, :edit, :destroy]

  def index
  end

  def show
  end

  def new
    @item = Item.find(params[:item_id])
    @item_location.item = @item
  end

  def create
    @item_location = ItemLocation.new(create_params)

    @item_location.save

    redirect_to item_item_location_url :id => @item_location.id
  end

  private
    def create_params
      params.require(:item_location).permit(:item_id, :warehouse_id, :in_stock, :quantity, :state)
    end
end

app/views/item_locations/_form.html.erb
<%= form_for(@item_location, :url => item_item_locations_path, :html => {:class => 'form-horizontal'}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :item_id %>
  <fieldset class="form-group">
    <%= f.label :quantity, :class => 'form-control-label col-sm-2' %>
    <div class="col-sm-1">
      <%= f.number_field :quantity, :class => 'form-control' %>
    </div>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :warehouse, :class => 'form-control-label col-sm-2' %>
    <div class="col-sm-3">
      <%= f.collection_select(:warehouse_id, Warehouse.all, :id, :name, {}, {:class => 'form-control c-select'}) %>
    </div>
  </fieldset>
  <fieldset class="form-group">
    <div class="col-sm-2">
      <p><%= t 'helpers.label.item_locations.state' %></p>
    </div>
    <div class="col-sm-2">
      <% ItemLocation.available_states.each do |state| %>
          <div class="radio">
            <label>
              <%= f.radio_button :state, state %> <%= t "helpers.label.item_locations.#{state}" %>
            </label>
          </div>
      <% end %>
    </div>
  </fieldset>
  <fieldset class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= link_to item_path(@item), :class => 'btn btn-danger' do %>
          <%= fa_icon 'undo' %>&nbsp;<%= t 'actions.cancel' %>
      <% end %>
      <%= button_tag(:class => 'btn btn-success') do %>
          <%= fa_icon 'save' %>&nbsp;<%= t 'actions.save' %>
      <% end %>
    </div>
  </fieldset>
<% end %>

app/views/item_locations/index.html.erb
<%= render 'shared/no_results' %>

app/views/item_locations/new.html.erb
<% provide(:title, (t 'item_locations.title.new')) %>

<h1><%= t 'item_locations.title.new_for_item', :item => @item.name %></h1>

<%= render 'form' %>

app/views/item_locations/show.html.erb
<% provide(:title, (t 'item_locations.title.show')) %>

<h1>
  <%= t 'item_locations.title.show' %>
</h1>

<div class="col-md-6 col-sm-12">
  <table class="table table-bordered table-hover">
    <tbody>
    <tr>
      <th class="th-inverse"><%= t 'helpers.label.item_location.item' %></th>
      <td><%= @item_location.item_name %></td>
    </tr>
    <tr>
      <th class="th-inverse"><%= t 'warehouses.title.singular' %></th>
      <td><%= @item_location.warehouse.presentation %></td>
    </tr>
    <tr>
      <th class="th-inverse"><%= t 'helpers.label.item_locations.quantity' %></th>
      <td><%= @item_location.quantity %></td>
    </tr>
    <tr>
      <th class="th-inverse"><%= t 'item_locations.type.label' %></th>
      <td><%= t "helpers.label.item_locations.#{@item_location.state}" %></td>
    </tr>
    </tbody>
  </table>
  <%= link_to item_path(@item_location.item), :class => 'btn btn-secondary' do %>
    <%= fa_icon 'undo' %>&nbsp;<%= t 'actions.back' %>
  <% end %>
</div>