config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /en|pl/ do
    root 'home#index'

    get '/sign_in', to: 'user_sessions#new', as: :sign_in
    post '/sign_in', to: 'user_sessions#create'
    delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out

    resources :warehouses
    resources :users do
      get '/user_status_info', to: 'users#statuses', as: :get_user_status
      put '/user_status', to: 'users#update_status', as: :update_user_status
    end
    resources :items do
      resources :item_locations
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :item_locations, inverse_of: :item, dependent: :delete_all
  has_many :warehouses, through: :item_locations

  def quantities
    data = {}

    self.warehouses.each do |warehouse|
      key = warehouse.presentation
      location = {}

      ItemLocation.available_states.each do |state|
        location[state] = self.item_locations.in_state(warehouse, state).sum(:quantity)
      end

      data[key] = location
    end

    data
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource :only => [:index, :show, :new, :edit, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @item = Item.new(resource_params)

    if @item.save
      flash[:success] = t 'flashes.save.success'

      redirect_to @item
    else
      flash[:error] = t 'flashes.save.error'

      render 'new'
    end
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(resource_params)
      flash[:success] = t 'flashes.update.success'

      redirect_to @item
    else
      flash[:error] = t 'flashes.update.error'

      render 'edit'
    end
  end

  private
  def resource_params
    params.require(:item).permit(:name, :description)
  end
end

app/views/items/_form.html.erb
<%= form_for @item, :html => {:class => 'form-horizontal'} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <fieldset class="form-group">
    <%= f.label :name, class: 'form-control-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </fieldset>
  <fieldset class="form-group">
    <%= f.label :description, :class => 'form-control-label' %>
    <%= f.text_area :description, :class => 'form-control' %>
  </fieldset>
  <fieldset class="form-group pull-right">
    <%= link_to items_path, :class => 'btn btn-danger' do %>
      <%= fa_icon 'undo' %>&nbsp;<%= t 'actions.cancel' %>
    <% end %>
    <%= button_tag(:class => 'btn btn-success') do %>
      <%= fa_icon 'save' %>&nbsp;<%= t 'actions.save' %>
    <% end %>
  </fieldset>
<% end %>

app/views/items/edit.html.erb
<% provide(:title, (t 'items.title.update')) %>

<h1><%= t 'items.title.update' %></h1>

<div class="col-md-6 col-sm-12">
  <%= render 'form' %>
</div>

app/views/items/index.html.erb
<% provide(:title, (t 'items.title.index')) %>

<h1>
  <%= t 'items.title.index' %>
  <%= link_to new_item_path, :class => 'btn btn-warning pull-right' do %>
    <%= fa_icon 'plus' %>&nbsp;<%= t 'items.title.new' %>
  <% end %>
</h1>
<% if @items.blank? %>
  <%= render 'shared/no_results' %>
<% else %>
  <table class="table table-bordered table-striped table-hover">
    <thead class="thead-inverse">
      <tr>
        <th>#</th>
        <th><%= t 'helpers.label.item.name' %></th>
        <th><%= t 'helpers.label.item.description' %></th>
        <th class="text-xs-center"><%= fa_icon 'cogs' %></th>
      </tr>
    </thead>
    <tbody>
    <% @items.each_with_index do |item, index| %>
      <tr class="row-linkable" data-url="<%= item_path(item) %>">
        <th scope="row"><%= index + 1 %></th>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td class="text-xs-center">
          <ul class="list-inline">
            <li class="list-inline-item">
              <%= action_show item_path(item) %>
            </li>
            <li class="list-inline-item">
              <%= action_edit edit_item_path(item) %>
            </li>
            <li class="list-inline-item">
              <%= action_delete item_path(item) %>
            </li>
          </ul>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/items/new.html.erb
<% provide(:title, (t 'items.title.new')) %>

<h1><%= t 'items.title.new' %></h1>

<div class="col-md-6 col-sm-12">
  <%= render 'form' %>
</div>

app/views/items/show.html.erb
<% provide(:title, (t 'items.title.show')) %>

<h1>
  <%= t 'items.title.show' %>
</h1>

<div class="col-md-6 col-sm-12">
  <table class="table table-bordered table-hover">
    <tbody>
    <tr>
      <th class="th-inverse"><%= t 'helpers.label.item.name' %></th>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <th class="th-inverse"><%= t 'helpers.label.item.description' %></th>
      <td><%= @item.description %></td>
    </tr>
    <tr>
      <th class="th-inverse">
        <%= t 'helpers.label.item.item_locations' %>
        <%= link_to new_item_item_location_path(@item), :class => 'btn btn-warning pull-right' do %>
            <%= fa_icon 'plus' %>&nbsp;<%= t 'item_locations.actions.add' %>
        <% end %>
      </th>
      <td>
        <% @item.quantities.each do |warehouse, values| %>
          <h6><%= warehouse %></h6>
          <dl class="dl-horizontal">
            <% ItemLocation.available_states.each do |state| %>
                <dt class="col-sm-6"><%= t "helpers.label.item_locations.#{state}" %>:</dt>
                <dd class="col-sm-6"><%= values[state] %></dd>
            <% end %>
          </dl>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
  <%= link_to items_path, :class => 'btn btn-secondary' do %>
    <%= fa_icon 'list' %>&nbsp;<%= t 'actions.list' %>
  <% end %>
  <%= link_to edit_item_path(@item), :class => 'btn btn-primary pull-right' do %>
    <%= fa_icon 'wrench' %>&nbsp;<%= t 'actions.edit' %>
  <% end %>
</div>